

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: password
    platform: postgres
    driver-class-name:
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: campsite
        hbm2ddl:
          auto: none
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    schemas: campsite
    locations: classpath:db/migration/common
    table: flyway_history
    validateOnMigrate: false


server:
  port: 8080
  max-http-header-size: 65536

