

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: campite
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    enabled: true
    schemas: campite
    locations: classpath:db/migration/common
    table: flyway_history
    validateOnMigrate: false


server:
  port: 8080
  max-http-header-size: 65536

