swagger: '2.0'
info:
  title: New Pacific Island Campsite API
  description: An API, that exposes the endpoints for availabilites and reservations of the campsite on the newest pacific island.
  version: '2.0'
host: localhost:8080
basePath: /
paths:
  /availabilities:
    get:
      summary: Returns a list of availabilities.
      operationId: getAvailabilities

      description: This list is a list of all availabilities of the campsite within the date range.
      parameters:
        - name: startDate
          in: query
          description: Start date for searching reservations.
          required: true
          type: string
          format: date
        - name: endDate
          in: query
          description: End date for searching reservations. If not provided 1 month since start date is used.
          required: false
          type: string
          format: date
      responses:
        '200':    # status code
          description: A JSON array of availabilities
          schema:
            type: array
            items:
              $ref: '#/definitions/Availabilities'
        '400':    # status code
          description: Bad Request
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'
        '404':
          description: No availabilities found.
          schema:
            type: array
            items:
              type: string


  /reservations:
    get:
      summary: Returns reservations.
      description: Returns reservation.
      operationId: getReservations

      responses:
        '200':
          description: Creation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'

        '404':
          description: Reservations not found

        '400':
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/Error'

        '500':    # status code
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/Error'

    post:
      summary: Creates a reservation.
      operationId: saveReservation
      description: Creates a reservation.

      responses:
        '201':
          description: Creation succesfull
          schema:
            type: object
        '400':    # status code
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/Error'
        '409':    # status code
          description: Could not save. Conflict with existing resource.
          schema:
            items:
              $ref: '#/definitions/Error'

        '500':    # status code
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/Error'


  /reservations/{id}:
    get:
      summary: Returns a reservation.
      description: Optional extended description in CommonMark or HTML.
      operationId: getReservation
      parameters:
        - name: id
          in: path
          description: Reservation Id
          required: true
          type: string
      responses:
        '200':    # status code
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'

        '404':    # status code
          description: Reservation not found

        '400':    # status code
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/Error'

        '500':    # status code
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/Error'

    delete:
      summary: Cancels a reservation.
      description: Cancels (Deletes) a reservation.
      operationId: deleteReservation
      parameters:
        - name: id
          in: path
          description: Reservation Id
          required: true
          type: string
      responses:
        '204':
          description: The resource was deleted successfully.

        '404':    # status code
          description: Reservation not found
          schema:
            items:
              $ref: '#/definitions/Error'

        '400':    # status code
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/Error'

        '500':    # status code
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/Error'

    patch:
      summary: Modifies a reservation.
      description: Modifies a reservation.
      operationId: modifyReservation
      parameters:
        - name: id
          in: path
          description: Reservation Id
          required: true
          type: integer
      responses:
        '200':
          description: Modification succesfull
          schema:
            items:
              $ref: '#/definitions/Reservation'

        '400':    # status code
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/Error'

        '500':    # status code
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/Error'

definitions:
  Reservation:
    type: object
    properties:
      id:
        description: Reservation Id
        type: integer
        format: int64
      fullname:
        description: Client's full name
        type: string
      email:
        description: Client's email address
        type: string
      arrivalDate:
        description: Client's arrival date
        type: string
        format: date
        example: yyyy-MM-dd
      departureDate:
        description: Client's departure date
        type: string
        format: date
        example: yyyy-MM-dd
      numberOfDays:
        description: Number of days
        type: integer
        format: int16
    required:
      - id
      - fullname
      - email
      - arrivalDate
      - numberOfDays
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  Availabilities:
    type: object
    description: List of available dates
    properties:
      availableDate:
        description: AvailableDate
        type: string
        format: date
        example: yyyy-MM-dd
